### ISSUE TITLE
Getting error during install of Qbix/Platform on tag v1.1

### ISSUE THREAD

**Issue by pavanyogi** [Qbix/Platform-History-v2#1715]
`pavany@u-16:.../Platform$ sudo php Teaching/scripts/Q/configure.php Teaching
missing file handlers/MyApp/after/Q_configure.php

in /home/project/Platform/platform/classes/Q.php (522)
#0 /home/project/Platform/platform/classes/Q.php(1087): Q::includeFile('handlers/MyApp/...', Array, true)
#1 /home/project/Platform/platform/classes/Q.php(987): Q::handle('MyApp/after/Q_c...', Array, false, NULL)
#2 /home/project/Platform/platform/classes/Q/Bootstrap.php(296): Q::event('Q/configure', Array, 'after')
#3 /home/project/Platform/platform/Q.php(115): Q_Bootstrap::configure()
#4 /home/project/Platform/Teaching/scripts/Q.inc.php(34): include('/home/project/P...')
#5 /home/project/Platform/Teaching/scripts/Q/configure.php(15): include('/home/project/P...')
#6 {main}
pavany@u-16:.../Platform$`

**Comment by pavanyogi** [comment]
We are getting errors in the install of this project. We are using PHP version 5.6 and the branch is checkout at tag v1.1. Any hint/help would be greatly appreciated.

**Comment by elizasviel** [comment]
Was this issue ever resolved? I am having the same problem with php configure

C:\wamp64\www\platform\Teaching\scripts\Q>php configure.php Teaching
missing file handlers\MyApp\after\Q_configure.php

in C:\wamp64\www\platform\platform\classes\Q.php (570)
#0 C:\wamp64\www\platform\platform\classes\Q.php(1143): Q::includeFile()
#1 C:\wamp64\www\platform\platform\classes\Q.php(1043): Q::handle()
#2 C:\wamp64\www\platform\platform\classes\Q\Bootstrap.php(323): Q::event()
#3 C:\wamp64\www\platform\platform\Q.php(115): Q_Bootstrap::configure()
#4 C:\wamp64\www\platform\Teaching\scripts\Q.inc.php(34): include('...')
#5 C:\wamp64\www\platform\Teaching\scripts\Q\configure.php(15): include('...')
#6 {main}

**Comment by EGreg** [comment]
Try now with latest version @pavanyogi  @elizasviel

**Comment by EGreg** [comment]
Did it work? @elizasviel
